# config.yml file
hippunfold: True

pybids_inputs:
  # Hippunfold
  hipp_surf:
    # Filters to look for surf files
    pybids_filters:
      extension: '.surf.gii'
      space: 'T1w'
      suffix: ['inner','midthickness','outer']
    # Scalars to attach to the surf
    scalars:
      labels:
        pybids_filters:
          extension: '.label.gii'
        match_entities: ['label', 'hemi']
        colortable: '/home/mcespedes/Documents/code/SlicerHippunfold/HippSlicer/Resources/Data/desc-subfields_atlas-bigbrain_dseg.tsv'
      shapes:
        pybids_filters:
          extension: '.shape.gii'
        match_entities: ['label', 'hemi']
  dentate_surf:
    # Filters to look for surf files
    pybids_filters:
      extension: '.surf.gii'
      space: 'T1w'
      suffix: ['inner','midthickness','outer']
    # Scalars to attach to the surf
    scalars:
      labels:
        pybids_filters:
          extension: '.label.gii'
        match_entities: ['label', 'hemi']
        colortable: '/home/mcespedes/Documents/code/SlicerHippunfold/HippSlicer/Resources/Data/desc-subfields_atlas-bigbrain_dseg.tsv'
      shapes:
        pybids_filters:
          extension: '.shape.gii'
        match_entities: ['label', 'hemi']
  dseg:
    pybids_filters:
      extension: '.nii.gz'
      suffix: 'dseg'
      datatype: 'anat'
  #fmriprep
  surf2:
    pybids_filters:
      extension: '.surf.gii'
      datatype: 'anat'

scalars:
  # Hippunfold
  labels:
    pybids_filters:
      extension: '.label.gii'
    colortable: '/home/mcespedes/Documents/code/SlicerHippunfold/HippSlicer/Resources/Data/desc-subfields_atlas-bigbrain_dseg.tsv'
  shapes:
    pybids_filters:
      extension: '.shape.gii'