# config.yml file
hippunfold: True

pybids_inputs:
  # Hippunfold
  surf:
    pybids_filters:
      extension: '.surf.gii'
      suffix: ['inner','midthickness','outer']
    custom_regex: "^.+_space-T1w_den-0p5mm_label-hipp_.+.surf.gii$"
  dseg:
    pybids_filters:
      extension: '.nii.gz'
      suffix: 'dseg'
      datatype: 'anat'
  #fmriprep
  surf2:
    pybids_filters:
      extension: '.surf.gii'
      datatype: 'anat'

scalars:
  # Hippunfold
  labels:
    pybids_filters:
      extension: '.label.gii'
    colortable: '/home/mcespedes/Documents/code/SlicerHippunfold/HippSlicer/Resources/Data/desc-subfields_atlas-bigbrain_dseg.tsv'
  shapes:
    pybids_filters:
      extension: '.shape.gii'